---
title: "Assignment 1 Data selection"
author: "Xiaofeng Li"
date: "2026-02-07"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true  
    code_folding: hide
bibliography: references.bib
link-citations: true
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  echo    = FALSE,
  warning = FALSE,
  message = FALSE,
  knitr.kable.max_rows = 6
)

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

pkgs_bioc <- c("GEOmetadb", "GEOquery", "biomaRt")
pkgs_cran <- c("DBI", "RSQLite", "tidyverse", "ggplot2")

for (p in pkgs_bioc) {
  if (!requireNamespace(p, quietly = TRUE))
    BiocManager::install(p, ask = FALSE)
}

for (p in pkgs_cran) {
  if (!requireNamespace(p, quietly = TRUE))
    install.packages(p)
}
library(tidyverse)
library(biomaRt)
library(GEOmetadb)
library(GEOquery)
library(DBI)
library(RSQLite)
library(DESeq2)
library(edgeR)
library(DESeq2)
library(limma)

getGEOSuppFiles("GSE104674")
```

# Finding Data

```{r}
sqlite_file <- getSQLiteFile()
con <- dbConnect(SQLite(), sqlite_file)
dbListTables(con)
rna_seq_gpl <- dbGetQuery(con, "
SELECT gpl
FROM gpl
WHERE technology LIKE '%high-throughput sequencing%'
")
human_rnaseq_gsm <- dbGetQuery(con, "
SELECT gsm.gsm, gsm.gpl
FROM gsm
WHERE organism_ch1 = 'Homo sapiens'
  AND gsm.gpl IN (
        SELECT gpl
        FROM gpl
        WHERE technology LIKE '%high-throughput sequencing%'
  )
")
human_rnaseq_gse <- dbGetQuery(con, "
SELECT DISTINCT gse_gsm.gse
FROM gse_gsm
WHERE gse_gsm.gsm IN (
    SELECT gsm
    FROM gsm
    WHERE organism_ch1 = 'Homo sapiens'
      AND gpl IN (
            SELECT gpl
            FROM gpl
            WHERE technology LIKE '%high-throughput sequencing%'
      )
)
")

diabetes_gse <- dbGetQuery(con, "
SELECT gse.gse, gse.title, gse.summary, gse.overall_design
FROM gse
WHERE gse.gse IN (
    SELECT DISTINCT gse
    FROM gse_gsm
    WHERE gsm IN (
        SELECT gsm
        FROM gsm
        WHERE organism_ch1 = 'Homo sapiens'
          AND gpl IN (
                SELECT gpl
                FROM gpl
                WHERE technology LIKE '%high-throughput sequencing%'
          )
    )
)
AND (
       gse.title LIKE '%diabetes%'
    OR gse.summary LIKE '%diabetes%'
    OR gse.overall_design LIKE '%diabetes%'
)
")
gse_sample_counts <- dbGetQuery(con, "
SELECT gse, COUNT(gsm) AS n_samples
FROM gse_gsm
GROUP BY gse
HAVING n_samples >= 10
")
final_gse <- Reduce(
    intersect,
    list(
        diabetes_gse$gse,
        gse_sample_counts$gse
    )
)
final_gse
final_info <- dbGetQuery(
    con,
    paste0(
        "SELECT gse, title, summary, overall_design
         FROM gse
         WHERE gse IN ('",
        paste(final_gse, collapse = "','"),
        "')"
    )
)

final_info
```

# Loading Data

```{r}
gse <- getGEO(
    "GSE104674",
    GSEMatrix = TRUE,
    getGPL = FALSE
)
eset <- gse[[1]]

counts <- read.table(
  "./GSE104674/GSE104674_rawCounts.txt.gz",
  header = TRUE,
  row.names = 1,
  sep = "\t",
  check.names = FALSE
)
pheno <- pData(eset)
pheno$group <- factor(
  ifelse(
    grepl("Healthy", pheno$characteristics_ch1),
    "control",
    "diabetes"
  ),
  levels = c("control", "diabetes")
)
pheno <- pheno %>%
  mutate(
    subject_id = str_extract(characteristics_ch1.1, "\\d+$"),
    subject_id = str_pad(subject_id, width = 2, side = "left", pad = "0"),
    timepoint  = str_extract(title, "D\\d+:\\d+"),
    timepoint  = str_replace(timepoint, ":", "_"),
    sample_name = paste0("Rhythm", subject_id, "_", timepoint)
  )
rownames(pheno) <- pheno$sample_name
pheno <- dplyr::select(pheno, group)
```

# ID mapping

### Raw counts format

```{r}
head(rownames(counts))
```

We can find the format of gene identifier is `gene_name:transcript_ID`. Thus, we need to merge all transcripts of one gene into a single count. \### Mapping

```{r}
head(rownames(counts))
gene_symbol <- sub(":.*$", "", rownames(counts))
counts_df <- data.frame(
  gene_symbol = gene_symbol,
  counts,
  check.names = FALSE
)
counts_final <- counts_df %>%
  group_by(gene_symbol) %>%
  summarise(across(where(is.numeric), sum))
counts_final <- as.data.frame(counts_final)
rownames(counts_final) <- counts_final$gene_symbol
counts_final$gene_symbol <- NULL
```

## Data distribution

### Density plot（log2 counts）

```{r}
counts_final <- as.matrix(counts_final)
log_counts <- log2(counts_final + 1)
plotDensities(log_counts, legend = FALSE, main ="log2 density plot")
```

### Boxplot

```{r}
plot_box <- function(mat, pheno, main = "", ylab = "log2(counts+1)") {
  df_long <- as.data.frame(mat) |>
    rownames_to_column("gene") |>
    pivot_longer(-gene, names_to = "sample", values_to = "value") |>
    left_join(pheno |> rownames_to_column("sample"), by = "sample") |>
    mutate(value = log2(value + 1))

  overall_mean <- mean(df_long$value, na.rm = TRUE)

  ggplot(df_long, aes(x = sample, y = value, fill = group)) +
    geom_boxplot(outlier.size = 0.3, alpha = 0.8) +
    geom_hline(yintercept = overall_mean, color = "red", linewidth = 0.6) +
    scale_fill_manual(values = c(control = "#1F3A8A", diabetes = "#F59E0B")) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(title = main, x = "Sample", y = ylab)
}

p_raw <- plot_box(counts_final, pheno, main = "Raw counts")
p_raw
```

## TMM normalization（edgeR）

```{r}
dge <- DGEList(counts = counts_final, group = pheno$group)
dge <- calcNormFactors(dge, method = "TMM")

logCPM <- cpm(dge, log = TRUE, prior.count = 1)
```

## MDS plot

```{r}
plotMDS(
  logCPM,
  col = col_group,
  labels = NULL
)

legend(
  "topright",
  legend = levels(pheno$group),
  col = c("#1F3A8A", "#F59E0B"),
  pch = 16
)
```

## Comparsion

```{r}
plot_box_overlay <- function(raw_mat, norm_mat,
                             ylab = "log2(counts+1)") {

  df_raw <- as.data.frame(raw_mat) |>
    rownames_to_column("gene") |>
    pivot_longer(-gene, names_to = "sample", values_to = "value") |>
    mutate(
      value = log2(value + 1),
      type = "Raw"
    )

  df_norm <- as.data.frame(norm_mat) |>
    rownames_to_column("gene") |>
    pivot_longer(-gene, names_to = "sample", values_to = "value") |>
    mutate(
      value = log2(value + 1),
      type = "TMM"
    )

  df_long <- bind_rows(df_raw, df_norm)

  ggplot(df_long, aes(x = sample, y = value, fill = type)) +
    geom_boxplot(
      position = "identity",
      alpha = 0.4,
      outlier.size = 0.3
    ) +
    scale_fill_manual(
      values = c(Raw = "blue", TMM = "red")
    ) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1)
    ) +
    labs(x = "Sample", y = ylab, fill = "")
}
plot_box_overlay(counts_final, 2^logCPM)
```

## DESeq2

```{r, message=FALSE}
keep <- rowSums(counts_final >= 10) >= 3
counts_final <- counts_final[keep, ]
dds <- DESeqDataSetFromMatrix(
  countData = counts_final,
  colData = pheno,
  design = ~ group
)

dds <- DESeq(dds)
res <- results(dds, contrast = c("group", "diabetes", "control"))
res_df <- as.data.frame(res) |> rownames_to_column("gene")
```

## Volcano Plot

```{r volcano}
res_df <- res_df |>
  mutate(sig = case_when(
    padj < 0.05 & log2FoldChange > 1  ~ "Up",
    padj < 0.05 & log2FoldChange < -1 ~ "Down",
    TRUE ~ "NS"
  ))

ggplot(res_df, aes(x = log2FoldChange, y = -log10(padj), color = sig)) +
  geom_point(size = 1.2, alpha = 0.8) +
  scale_color_manual(values = c(Up = "red", Down = "blue", NS = "grey")) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  theme_bw() +
  labs(title = "Volcano plot", x = "log2 Fold Change", y = "p-value(-log10)")
```
